# Node.js Build Pipeline for React Deployment on IIS

trigger:
- main  # Se ejecuta la build en cada push a main

pool:
  vmImage: ubuntu-latest

steps:
# 1️⃣ Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# 2️⃣ Instalar dependencias y construir la aplicación
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# 3️⃣ Publicar los artefactos (IMPORTANTE)
# Asegura que los archivos generados en /build sean accesibles en la Release Pipeline

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build'  # ✅ Ruta corregida
    Contents: '**'  
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/build'
    artifactName: 'drop'  # ✅ Se mantiene el nombre del artefacto
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
