# Node.js Build Pipeline for React Deployment on IIS

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Instalar Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Instalar dependencias y construir la aplicación
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publicar los artefactos (IMPORTANTE)
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'  # Carpeta donde React genera los archivos de producción
    Contents: '**'         # Copia todos los archivos dentro de /build
    TargetFolder: '$(Build.ArtifactStagingDirectory)/build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/build'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
